### ISSUE TITLE
The hosted query path requires an internal service, so a pipeline cannot be composed outside AddCratisArc

### ISSUE THREAD

**Issue by einari** [Cratis/Arc#2753]
## What happens

The hosted query path resolves `AuthorizationPrincipalScope` from the request's service provider, and
that type is `internal` to `Cratis.Arc.Core`. A consumer that composes the query pipeline from its
individual services therefore cannot make it work: the service cannot be registered from outside the
assembly, and every request answers 500.

```csharp
// QueryPipeline.PerformHostedCore, 22.23.0
principalLease.Attach(serviceProvider.GetRequiredService<AuthorizationPrincipalScope>().Begin(selectedPrincipal, serviceProvider));
```

```csharp
// AuthorizationPrincipalScope.cs
internal class AuthorizationPrincipalScope(
```

Registering it from a consuming assembly does not compile:

```
error CS0122: 'AuthorizationPrincipalScope' is inaccessible due to its protection level
```

`AuthorizationDeclarations` and `AuthorizationEvaluation`, resolved on the same path, are public and can
be registered. `AuthorizationPrincipalScope` is the one that cannot.

## Why it matters

A test harness that assembles the pipeline service by service - deliberately, to exercise one transport
against the real `QueryPipeline`, `QueryFilters`, `QueryRenderers` and performer provider while leaving
application middleware out - worked on 22.22.0 and cannot be made to work on 22.23.0. The only way to
get a functioning pipeline now is `AddCratisArc()`, which brings in the middleware the harness exists to
exclude.

This also means the set of services the hosted path needs is not discoverable from outside: each one
surfaces as a runtime resolution failure, and the last one cannot be satisfied at all.

## Expected

Either the hosted path takes what it needs as constructor dependencies of `QueryPipeline`, so the
requirement is visible in the signature and satisfiable by anyone composing it, or
`AuthorizationPrincipalScope` becomes public like its neighbours on the same path.

## Environment

Arc 22.23.0, .NET 10. Worked on 22.22.0. Found in Cratis/Studio, which is holding at 22.22.0 because of
this.
